#!/usr/bin/env bash
if [ "$#" -lt 2 ]; then
	echo "./addpython file_name description [function_prototype function_description]"
else
	echo -e "#!/usr/bin/python3\n\"\"\"\n    $2\n\"\"\"\n" > "$1"
	chmod u+x "$1"
	echo -e "### $1\n* $2\n" >> README.md
fi
if [ "$#" -ge 3 ]; then
	echo -e "\n$3\n    \"\"\"\n        $4\n    \"\"\"\n" >> "$1"
	echo -e "  * Prototype: \`$3\`\n" >> README.md
fi
