#!/bin/bash
wget http://dev.mysql.com/get/mysql-apt-config_0.6.0-1_all.deb # From https://dev.mysql.com/downloads/repo/apt/
sudo dpkg -i mysql-apt-*.deb
sudo apt-key adv --keyserver pgp.mit.edu --recv-keys A4A9406876FCBD3C456770C88C718D3B5072E1F5
sudo apt-get update
sudo apt-get -y install mysql-server
